# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd5dcafc4ae024fe062d0d94a2f425c997d13a5a1aca24eae73245a7439758b175988cf5b8856eb7ef29ed5e72e52a18f1ab6dff573aa8200ea32080b51e5997

test:
  secret_key_base: a990ae5ade675ef0ada453ee54357fc4105233f1aa29a780c41c51eff233b1df50178ebb62d86d7670d12f2d6269b049afe7abc19bc33f3a04a4296d54889135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
